<a href="https://colab.research.google.com/github/alijonovanargiza28/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv("StudentsPerformance_csv")
print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist())

print("First 5 rows of the dataset:")
print(df.head())

print("Summary statistics:")
print(df.describe())

print("Data type and null info")
print(df.info())

Dataset shape (rows, columns): (2392, 15)
Column name: ['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation', 'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA', 'GradeClass']
First 5 rows of the dataset:
   StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723
1       1002   18       0          0                  1        15.408756
2       1003   15       0          2                  3         4.210570
3       1004   17       1          0                  3        10.028829
4       1005   17       1          0                  2         4.672495

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1
1         0         0                1                0       0      0
2        26         0                2                0       0      0
3        14         0                3                1       0      0
4        17         1                3                0       0      0

   Volunteering       GPA  GradeClass
0             0  2.929196         2.0
1             0  3.042915         1.0
2             0  0.112602         4.0
3             0  2.054218         3.0
4             0  1.288061         4.0
Summary statistics:
         StudentID          Age       Gender    Ethnicity  ParentalEducation  \
count  2392.000000  2392.000000  2392.000000  2392.000000        2392.000000
mean   2196.500000    16.468645     0.510870     0.877508           1.746237
std     690.655244     1.123798     0.499986     1.028476           1.000411
min    1001.000000    15.000000     0.000000     0.000000           0.000000
25%    1598.750000    15.000000     0.000000     0.000000           1.000000
50%    2196.500000    16.000000     1.000000     0.000000           2.000000
75%    2794.250000    17.000000     1.000000     2.000000           2.000000
max    3392.000000    18.000000     1.000000     3.000000           4.000000

       StudyTimeWeekly     Absences     Tutoring  ParentalSupport  \
count      2392.000000  2392.000000  2392.000000      2392.000000
mean          9.771992    14.541388     0.301421         2.122074
std           5.652774     8.467417     0.458971         1.122813
min           0.001057     0.000000     0.000000         0.000000
25%           5.043079     7.000000     0.000000         1.000000
50%           9.705363    15.000000     0.000000         2.000000
75%          14.408410    22.000000     1.000000         3.000000
max          19.978094    29.000000     1.000000         4.000000

       Extracurricular       Sports        Music  Volunteering          GPA  \
count      2392.000000  2392.000000  2392.000000   2392.000000  2392.000000
mean          0.383361     0.303512     0.196906      0.157191     1.906186
std           0.486307     0.459870     0.397744      0.364057     0.915156
min           0.000000     0.000000     0.000000      0.000000     0.000000
25%           0.000000     0.000000     0.000000      0.000000     1.174803
50%           0.000000     0.000000     0.000000      0.000000     1.893393
75%           1.000000     1.000000     0.000000      0.000000     2.622216
max           1.000000     1.000000     1.000000      1.000000     4.000000

        GradeClass
count  2392.000000
mean      2.983696
std       1.233908
min       0.000000
25%       2.000000
50%       4.000000
75%       4.000000
max       4.000000
Data type and null info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB
None

In [15]:
print("Average score by columns:")

df[["GPA", "StudyTimeWeekly", "Absences"]].mean()

Average score by columns:

GPA                 1.906186
StudyTimeWeekly     9.771992
Absences           14.541388
dtype: float64

In [16]:
print("Maximum values by columns:")

df[["GPA", "StudyTimeWeekly", "Absences"]].max()

Maximum values by columns:

GPA                 4.000000
StudyTimeWeekly    19.978094
Absences           29.000000
dtype: float64

In [17]:
print("Maximum values by columns:")

df[["GPA", "StudyTimeWeekly", "Absences"]].min()

Maximum values by columns:

GPA                0.000000
StudyTimeWeekly    0.001057
Absences           0.000000
dtype: float64

In [19]:
# correlation
print("Correlation")
df[["GPA", "StudyTimeWeekly", "Absences"]].corr()

Correlation

                      GPA  StudyTimeWeekly  Absences
GPA              1.000000         0.179275 -0.919314
StudyTimeWeekly  0.179275         1.000000  0.009326
Absences        -0.919314         0.009326  1.000000

In [21]:
import numpy as np

# GPA asosida foizli ball yaratish (0–100)
df["Total score"] = df["GPA"] / 4 * 100

# O'rtacha ball
df["average score"] = df["Total score"]

# O'tgan yoki o'tmaganini aniqlash
df["passed"] = np.where(df["GPA"] >= 2.0, "Yes", "No")

# Natijani ko'rish
print("New colums preview (total, average, passed):")
df[["GPA", "Total score", "average score", "passed"]].head()

New colums preview (total, average, passed):

        GPA  Total score  average score passed
0  2.929196    73.229890      73.229890    Yes
1  3.042915    76.072871      76.072871    Yes
2  0.112602     2.815056       2.815056     No
3  2.054218    51.355453      51.355453    Yes
4  1.288061    32.201530      32.201530     No

In [22]:
import numpy as np

# 1. Tutoring bo'yicha o'rtacha GPA
tutoring_group = df.groupby("Tutoring")[["GPA", "StudyTimeWeekly"]].mean()
print("Student performance by tutoring:")
print(tutoring_group)

# 2. Gender bo'yicha o'rtacha natijalar
gender_avg = df.groupby("Gender")[["GPA", "StudyTimeWeekly", "Absences"]].mean()
print("Average score by gender:")
print(gender_avg)

# 3. O'tgan va o'tmagan talabalar foizi
df["passed"] = np.where(df["GPA"] >= 2.0, "Yes", "No")

pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Pass rate:\n", pass_rate)

Student performance by tutoring:
               GPA  StudyTimeWeekly
Tutoring
0         1.818968         9.664592
1         2.108325        10.020903
Average score by gender:
             GPA  StudyTimeWeekly   Absences
Gender
0       1.918679         9.705749  14.355556
1       1.894225         9.835416  14.719313
Pass rate:
 passed
No     53.26087
Yes    46.73913
Name: proportion, dtype: float64

In [23]:
import numpy as np

# Convert data to NumPy array
scores = df[["GPA", "StudyTimeWeekly", "Absences"]].values

# Mean, Standard Deviation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std:", np.std(scores, axis=0))

# Z-score (normalization)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)

print("Z-scores (normalized numbers):")
print(z_score[:5])

Numpy Mean: [ 1.9061863   9.77199192 14.54138796]
Numpy Std: [0.91496451 5.65159251 8.46564725]
Z-scores (normalized numbers):
[[ 1.11808631  1.78033552 -0.89082237]
 [ 1.24237446  0.99737625 -1.71769358]
 [-1.96027719 -0.98404514  1.35354235]
 [ 0.1617897   0.04544517 -0.06395116]
 [-0.67557279 -0.90231145  0.29042222]]

In [24]:
import numpy as np

# How many students scored above 90?
top_scores = df[df["GPA"] / 4 * 100 >= 90]
print("Top scored students above 90:", len(top_scores))

# How many failed?
df["passed"] = np.where(df["GPA"] >= 2.0, "Yes", "No")

failed = df[df["passed"] == "No"]
print("Failed from exam:", len(failed))

Top scored students above 90: 39
Failed from exam: 1274